Yazan habit creation
CMPUT301F21T05/TheGreatGitastrophe pull request #30
Opened 2021-11-04 01:08 UTC by crankdank

Added my habits activity, a fragment for creating habits, and only the ability to add in habits. Editing habits and removing habits remain to be implemented, as well as a habit validity check

2021-11-04 03:26 UTC, ccchoi2 requested changes

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/HabitFragments.java
> +            Habit Retrieved_Habit = (Habit)args.getSerializable("habit");
I think we should keep our variable naming convention consistent, others use lower camel case with no underscores

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/HabitFragments.java
> +        else {
This chunk of code under here seems identical to the code above starting from line 103. I don't think there's a reason to lock it into a conditional then. Perhaps just put what's different (lines 100-102) inside the conditional and only have one instance of this giant chunk of code.

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/MyHabits.java
> +    private RecyclerViewAdapter adapter2;
I can't seem to find another adapter item, so why is this the second? Perhaps a more descriptive name of what this adapter is.

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/MyHabits.java
> +    }
Why is there an empty function here?

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/RecyclerViewAdapter.java
> +                    //Edit_frag.show(this,"EDIT_CITY");
please cleanup all these commented lines of code

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/res/values/strings.xml
> +    <string name="second_fragment_label">Second Fragment</string>
what are these? more descriptive names if these are necessary?

2021-11-04 03:26 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/res/values/strings.xml
> +    <string name="hello_second_fragment">Hello second fragment. Arg: %1$s</string>
same question with these as above

2021-11-04 03:26 UTC, ccchoi2 commented on ProjectPart2.txt
> +Product Backlog for habit app demand:
Why does this txt file exist? If it's a test file, please keep it local to your machine

2021-11-04 04:03 UTC, adiep2 approved these changes
Looks good just need to address Calvin's comments.  Will approve since its just comment and variable name changes and also so we don't need to wait on it later

2021-11-05 05:44 UTC, ccchoi2 approved these changes

2021-11-05 05:44 UTC, merged