Feature/habit events
CMPUT301F21T05/TheGreatGitastrophe pull request #45
Opened 2021-11-21 05:39 UTC by Ryden-Graham

Got basic habit event functionality integrated with the "today's habits" page.
To interface with habits, use the methods in Account.
Habits events currently have an extra "holder" field used locally for the "today's habits" page, but unsaved on firestore
(firestore cannot save complex types, and new holders are created on load anyway if needed. Having the local variable just helps synchronize holders and events).

NOTE: Account only returns copies of its events to avoid the holders being saved to the sever. If you ever need to interface with habit events, do NOT simply redirect pointers (we want to try and restrict access to the main event lists).

Additional changes:
- Added password resets
- Added a password check to the username/pfp update page
- Removed a bunch of commented code

Many tests are currently broken; we will fix them after friends are added and there are no more core changes that could break them again.

2021-11-21 19:22 UTC, hibaqw approved these changes
Looks great!

2021-11-26 04:03 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/ChangePasswordFragment.java
> +                if (oldPassword.equals(newPassword)) {
wrong comment

2021-11-26 04:04 UTC, ccchoi2 commented on CMPUT_301_Project/app/src/main/java/com/example/cmput_301_project/UserProfilePage.java
> +        if (passwordVerified) {
remove this

2021-11-26 04:37 UTC, adiep2 requested changes
There is a bug when editing the habits causing it to not show up on the daily habit page.  If you create a habit with no other habits in the list then edit the frequency to include today it will not update the daily habit page.
Steps to reproduce:
1. Clear all habits
2. Add a habit without today in the frequency
3. Edit habit to include today in the frequency
4. Habit does not show up in daily habits page

2021-11-26 05:44 UTC, calchoi028 approved these changes
LGTM

2021-11-26 05:48 UTC, adiep2 approved these changes
Looks good!

2021-11-26 05:53 UTC, merged