My Friends Page
CMPUT301F21T05/TheGreatGitastrophe pull request #50
Opened 2021-11-25 23:01 UTC by adiep2

2021-11-25 23:37 UTC, ccchoi2 approved these changes
LGTM! 🚀

2021-11-25 23:56 UTC, Matheus-Du requested changes
Looks good, just a couple small things to look at and one typo in a textView.

2021-11-25 23:56 UTC, Matheus-Du commented on CMPUT_301_Project/app/src/main/res/layout/activity_add_friends.xml
> +    <androidx.fragment.app.FragmentContainerView
Navbar comes up with keyboard to block some of the screen. Not an issue per se but might look better to not have this. I'll leave it up to you.

![image](https://user-images.githubusercontent.com/20523379/143508667-e2630342-03e3-4130-9f10-5a8d109c280a.png)

2021-11-25 23:56 UTC, Matheus-Du commented on CMPUT_301_Project/app/src/main/res/layout/activity_add_friends.xml
> +        android:id="@+id/textView"
Can either remove id or make it more specific

2021-11-25 23:56 UTC, Matheus-Du commented on CMPUT_301_Project/app/src/main/res/layout/activity_my_friends.xml
> +        android:id="@+id/textView"
Can probably remove this id or make it more specific

2021-11-25 23:56 UTC, Matheus-Du commented on CMPUT_301_Project/app/src/main/res/layout/activity_my_friends.xml
> +            android:text="Click Any Habit to Delete It"
Should prompt to remove friends instead of delete habits

2021-11-26 00:20 UTC, Matheus-Du approved these changes

2021-11-26 00:21 UTC, merged